"""empty message

Revision ID: 00822681863f
Revises: d0ba7b8715e3
Create Date: 2021-04-30 14:43:38.609027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00822681863f'
down_revision = 'd0ba7b8715e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_state',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('expert_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('connected', sa.Boolean(create_constraint=False), nullable=False),
    sa.Column('current_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_problem_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.PrimaryKeyConstraint('expert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_state')
    # ### end Alembic commands ###
