"""empty message

Revision ID: 096e1cc3d33f
Revises: 4e350505fcbb
Create Date: 2021-05-05 23:44:44.456608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '096e1cc3d33f'
down_revision = '4e350505fcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('messages', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
