"""empty message

Revision ID: 1aa03115d124
Revises: d64ef61d5cf7
Create Date: 2021-05-08 20:48:54.167075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aa03115d124'
down_revision = 'd64ef61d5cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_state', 'failed_reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_state', sa.Column('failed_reason', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
