"""empty message

Revision ID: 30b6fb44bcb3
Revises: 97da22776566
Create Date: 2021-05-02 19:32:14.703252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b6fb44bcb3'
down_revision = '97da22776566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
