"""empty message

Revision ID: 3209251ff9fc
Revises: 74f80b7438fc
Create Date: 2021-04-21 13:11:16.039904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3209251ff9fc'
down_revision = '74f80b7438fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_rank', sa.Column('initial_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_rank', 'initial_score')
    # ### end Alembic commands ###
