"""empty message

Revision ID: 58e2a1a674b9
Revises: 8406617104ac
Create Date: 2021-05-02 15:43:29.227873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e2a1a674b9'
down_revision = '8406617104ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_state',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('num_bidding', sa.Integer(), nullable=False),
    sa.Column('routing_expiration', sa.DateTime(), nullable=True),
    sa.Column('chatting_expiration', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_state')
    # ### end Alembic commands ###
