"""empty message

Revision ID: 5b3eec7bb4f4
Revises: 93bfbc8bc7bb
Create Date: 2021-05-03 20:34:39.460264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b3eec7bb4f4'
down_revision = '93bfbc8bc7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_state', 'available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_state', sa.Column('available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
