"""empty message

Revision ID: 74f80b7438fc
Revises: 57fc2f7edc5b
Create Date: 2021-04-21 09:00:30.369924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74f80b7438fc'
down_revision = '57fc2f7edc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('nickname', sa.String(length=128), nullable=True))
    op.drop_column('expert', 'google_id')
    op.drop_column('expert', 'last_name')
    op.drop_column('expert', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('first_name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('expert', sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('expert', sa.Column('google_id', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('expert', 'nickname')
    # ### end Alembic commands ###
