"""empty message

Revision ID: 8406617104ac
Revises: 00822681863f
Create Date: 2021-04-30 16:55:59.367617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8406617104ac'
down_revision = '00822681863f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_state', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.drop_constraint('expert_state_ibfk_1', 'expert_state', type_='foreignkey')
    op.create_foreign_key(None, 'expert_state', 'question', ['current_question_id'], ['id'])
    op.drop_column('expert_state', 'current_problem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_state', sa.Column('current_problem_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expert_state', type_='foreignkey')
    op.create_foreign_key('expert_state_ibfk_1', 'expert_state', 'question', ['current_problem_id'], ['id'])
    op.drop_column('expert_state', 'current_question_id')
    # ### end Alembic commands ###
