"""empty message

Revision ID: 922dc88dea20
Revises: 7b71983638c1
Create Date: 2021-04-13 21:23:40.908224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '922dc88dea20'
down_revision = '7b71983638c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_ibfk_1', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'package_id')
    op.add_column('user_subscription_package', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('user_subscription_package', sa.Column('number_of_questions', sa.Integer(), nullable=True))
    op.add_column('user_subscription_package', sa.Column('package_name', sa.String(length=128), nullable=True))
    op.add_column('user_subscription_package', sa.Column('package_type', sa.String(length=128), nullable=True))
    op.drop_constraint('user_subscription_package_ibfk_1', 'user_subscription_package', type_='foreignkey')
    op.drop_column('user_subscription_package', 'package_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription_package', sa.Column('package_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_subscription_package_ibfk_1', 'user_subscription_package', 'subscription_package', ['package_id'], ['id'])
    op.drop_column('user_subscription_package', 'package_type')
    op.drop_column('user_subscription_package', 'package_name')
    op.drop_column('user_subscription_package', 'number_of_questions')
    op.drop_column('user_subscription_package', 'amount')
    op.add_column('transaction', sa.Column('package_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_ibfk_1', 'transaction', 'subscription_package', ['package_id'], ['id'])
    # ### end Alembic commands ###
