"""empty message

Revision ID: 93bfbc8bc7bb
Revises: d9d708c60ff9
Create Date: 2021-05-03 15:43:22.492316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bfbc8bc7bb'
down_revision = 'd9d708c60ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('expert_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('grant_score', sa.Float(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_state.question_id'], ),
    sa.PrimaryKeyConstraint('question_id', 'expert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
