"""empty message

Revision ID: a185ae39c4a2
Revises: 8a531b7101a1
Create Date: 2021-05-02 15:53:27.976591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a185ae39c4a2'
down_revision = '8a531b7101a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'question', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    # ### end Alembic commands ###
