"""empty message

Revision ID: d0ba7b8715e3
Revises: 913e29544298
Create Date: 2021-04-27 15:09:15.166488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ba7b8715e3'
down_revision = '913e29544298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('payment_method', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert', 'payment_method')
    # ### end Alembic commands ###
