"""empty message

Revision ID: d64ef61d5cf7
Revises: 2bb20f0c9d79
Create Date: 2021-05-06 22:17:12.447574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64ef61d5cf7'
down_revision = '2bb20f0c9d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('number_of_questions', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('package_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'package_name')
    op.drop_column('transaction', 'number_of_questions')
    # ### end Alembic commands ###
