"""empty message

Revision ID: d9d708c60ff9
Revises: 30b6fb44bcb3
Create Date: 2021-05-03 15:42:07.441617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d708c60ff9'
down_revision = '30b6fb44bcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_state', sa.Column('available', sa.Boolean(create_constraint=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_state', 'available')
    # ### end Alembic commands ###
