"""empty message

Revision ID: dd09c5162d2e
Revises: 5b3eec7bb4f4
Create Date: 2021-05-04 23:48:58.386955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd09c5162d2e'
down_revision = '5b3eec7bb4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_rating', sa.Column('expert_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_rating', 'expert', ['expert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rating', type_='foreignkey')
    op.drop_column('user_rating', 'expert_id')
    # ### end Alembic commands ###
