"""empty message

Revision ID: f9d31e9df20a
Revises: 096e1cc3d33f
Create Date: 2021-05-06 20:12:52.461560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9d31e9df20a'
down_revision = '096e1cc3d33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_earning', 'score_avg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_earning', sa.Column('score_avg', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
